### ISSUE TITLE
error: OAuth has not been registered for this session

### ISSUE THREAD

**Issue by kalwani** [Twitter-Sentiment-Analysis/Front-end#3]

**Comment by asmitapoddar** [comment]
You can learn on how to do ROAuth authentication to access twitter API. You have to visit the Twitter developer website and make your own session. This one is ours so you don't have access.

There are many blogs available for that.

**Comment by somiyaa** [comment]
i am getting the same error.

**Comment by andreyciocan** [comment]
Looks like twitter changed the type of OAuth: https://stackoverflow.com/questions/9373157/twitter-and-roauth . Can you please guide us where to change the OAuth? Should we change in authentication.R ?

**Comment by asmitapoddar** [comment]
Yes, you would need to change authentication.R and use your own consumer_key, consumer_secret etc. to access tweets. Also, update the twitteR and ROAuth packages.

**Comment by andreyciocan** [comment]
It worked! I must mention that for the shiny app to work we must follow the readme.md and run the R scripts in order. Thanks for sharing your work with us!
