### ISSUE TITLE
positive.txt file is missing

### ISSUE THREAD

**Issue by somiyaa** [Twitter-Sentiment-Analysis/Front-end#4]

**Comment by sonali9696** [comment]
Yes, you have to download the file and change the path according to the location of the file on your computer. You may find positive-words.txt here: https://github.com/sonali9696/Twitter-Sentiment-Analysis-R-Tutorials/blob/master/positive-words.txt

Similarly negative-words.txt can be found here: https://github.com/sonali9696/Twitter-Sentiment-Analysis-R-Tutorials/blob/master/negative-words.txt
